spring.datasource.initialization-mode: never
hsqldb:
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:
    properties-hibernate-dialect: org.hibernate.dialect.HSQLDialect
    hibernate-hbm2ddl-auto: create-drop



h2:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    properties-hibernate-dialect:  org.hibernate.dialect.H2Dialect
    hibernate-hbm2ddl-auto: create-drop

